# Generated by Django 5.0.6 on 2024-05-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_rename_parentt_category_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="brands",
            new_name="brand",
        ),
    ]
