# Generated by Django 5.0.6 on 2024-06-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExerciseSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_volume", models.DecimalField(decimal_places=2, max_digits=5)),
                ("repetitions_number", models.IntegerField()),
                ("rest_time", models.DurationField()),
                ("is_spotted", models.BooleanField(default=False)),
                ("tempo", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="SetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("target", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("equipment", models.CharField(max_length=50)),
                ("muscle_group", models.CharField(max_length=60)),
                (
                    "sets",
                    models.ManyToManyField(
                        related_name="exercises", to="workouts.exerciseset"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exerciseset",
            name="set_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sets",
                to="workouts.settype",
            ),
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("notes", models.TextField()),
                ("duration", models.DurationField()),
                ("series_amount", models.IntegerField()),
                ("training_number", models.IntegerField()),
                (
                    "exercises",
                    models.ManyToManyField(
                        related_name="sessions", to="workouts.exercise"
                    ),
                ),
                (
                    "workout_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="workouts.workouttype",
                    ),
                ),
            ],
        ),
    ]
