# Generated by Django 5.0.6 on 2024-05-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="parentt",
            new_name="parent",
        ),
    ]
